### ISSUE TITLE
Add support for TES v1.1

### ISSUE THREAD

**Issue by uniqueg** [ga4gh/openapi-test-runner#11]
TES v1.1 has recently been released: https://github.com/ga4gh/task-execution-schemas/releases/tag/v1.1

Please
- [ ] provide updates (not replacements) for any tests that change
- [ ] add a `v1.1` `version` tag for any tests that remain the same
- [ ] add tests for any additional functionalities introduced through the version change, if any (probably not)

**Comment by LakiG** [comment]
For Task 1, since v1.1 is backwards compatible, there are no breaking changes in current tests.
For Task 3, we can add a test related to the filtering logic. The backend parameters seem like metadata. 
We can add version tags to the YAML test files as you mentioned in Task 2.

**Comment by uniqueg** [comment]
Thanks. Good point about backward compatibility (except for the `int64` to `int32` change). And indeed, for all tests compatible with both spec versions, tags should be added.

But given that there _are_ changes in the specs, I guess some new tests should be written specifically for the changed behaviors, wherever possible, as you suggest.
