### ISSUE TITLE
v1.1: allow wildcards in output paths

### ISSUE THREAD

**Issue by lbeckman314** [ga4gh/openapi-test-runner#17]
feat: allow wildcards in output paths ([#185](https://github.com/ga4gh/task-execution-schemas/pull/185))

Sourced from [v1.1 release page](https://github.com/ga4gh/task-execution-schemas/releases/tag/v1.1).

**Comment by vsmalladi** [comment]
@lbeckman314  can we close this?

**Comment by uniqueg** [comment]
Seems like. Will close it.
