### ISSUE TITLE
v1.1: Changing int64 to int32 for page_size and cpu_count

### ISSUE THREAD

**Issue by lbeckman314** [ga4gh/openapi-test-runner#19]
Changing int64 to int32 for page_size and cpu_count ([#175](https://github.com/ga4gh/task-execution-schemas/pull/175))

Sourced from [v1.1 release page](https://github.com/ga4gh/task-execution-schemas/releases/tag/v1.1).

Note: this might not be possible to test through the compliance suite. Feel free to close if so!

**Comment by vsmalladi** [comment]
@lbeckman314  can we close this?
