### ISSUE TITLE
v1.1: Adding streamable flag to tesInput 

### ISSUE THREAD

**Issue by lbeckman314** [ga4gh/openapi-test-runner#22]
Adding streamable flag to tesInput ([#157](https://github.com/ga4gh/task-execution-schemas/pull/157))

Sourced from [v1.1 release page](https://github.com/ga4gh/task-execution-schemas/releases/tag/v1.1).

**Comment by vsmalladi** [comment]
@lbeckman314 I think this can be close right?

**Comment by lbeckman314** [comment]
Closing as support for this included in the latest release. Thanks Venkat!
