### ISSUE TITLE
Add negative tag filter

### ISSUE THREAD

**Issue by LakiG** [ga4gh/openapi-test-runner#39]
Currently, the `--tag` CLI arg runs the tests for all the tags provided.

Allow users to do negative tag filtering. Add `--exclude-tags` CLI arg to run tests for all except the provided tags.
The `--tag` can be updated to `--include-tags` as well.

**Comment by uniqueg** [comment]
Just a minor thing: You should use dashes (`-`) instead of underscores (`_`) for POSIX-compliant command-line interfaces, so better to use `--include-tags` and `--exlude-tags`. Or perhaps `--include` and `--exclude` would be sufficient?

**Comment by LakiG** [comment]
Oh, that makes sense. We should dashes then.

I think `--include-tags` and `--exclude-tags` are better as they are self-explanatory. The `--include` and `--exclude` are a little ambiguous.

**Comment by LakiG** [comment]
Self-assigning this issue to me.
