### ISSUE TITLE
Trivial Documentation mistake

### ISSUE THREAD

**Issue by Rahuljagwani** [ga4gh/openapi-test-runner#63]
`templates` is not inside `tests`. 

[Link](https://github.com/elixir-cloud-aai/openapi-test-runner/blob/dev/docs/utility.md?plain=1#L36)

@uniqueg Should I make a PR for this or will it be too small of a change for a commit??

**Comment by uniqueg** [comment]
Sure, you can create a PR. No change is too small :)

**Comment by Rahuljagwani** [comment]
> Sure, you can create a PR. No change is too small :)

I think I don't have write access to this repository as I am not able to create a new branch.

**Comment by uniqueg** [comment]
Sorry @Rahuljagwani, I was away for a couple of days. I think you should have write permissions on the repo now. Let me know if not.

**Comment by uniqueg** [comment]
Closed by #64
